const slidesX: {title: string, caption: string | null, url: string, desc: string}[]  = [
    {title: "1917", caption: null, url: "./slidesImages/1917X.jpg", desc: "Summaries. April 6th, 1917. As an infantry battalion assembles to wage war deep in enemy territory, two soldiers are assigned to race against time and deliver a message that will stop 1,600 men from walking straight into a deadly trap."},
    {title: "Captain America", caption: "The Winter Soldier", url: "./slidesImages/captainAmericaX.jpg", desc: "As Steve Rogers struggles to embrace his role in the modern world, he teams up with a fellow Avenger and S.H.I.E.L.D agent, Black Widow, to battle a new threat from history: an assassin known as the Winter Soldier."},
    {title: "Fantastic Beasts", caption: "and Where To Find Them", url: "./slidesImages/fantasticBeastsX.jpg", desc: "In 1926, magizoologist Newt Scamander arrives in New York during his worldwide tour to research and rescue magical creatures as something mysterious leaves trails of destruction in the city, threatening to expose the wizarding world."},
    {title: "Hereditary", caption: null, url: "./slidesImages/hereditaryX.jpg", desc: "A grieving family is haunted by tragic and disturbing occurrences."},
    {title: "Jumanji", caption: "Welcome to the Jungle", url: "./slidesImages/jumanjiX.jpg", desc: "Four teenagers are sucked into a magical video game, and the only way they can escape is to work together to finish the game."},
    {title: "Jurassic Park", caption: null, url: "./slidesImages/jurassicParkX.jpg", desc: "An industrialist invites some experts to visit his theme park of cloned dinosaurs. After a power failure, the creatures run loose, putting everyone's lives, including his grandchildren's, in danger."},
    {title: "Oblivion", caption: null, url: "./slidesImages/oblivionX.jpeg", desc: "Jack Harper, a drone repairman stationed on Earth that has been ravaged by war with extraterrestrials, questions his identity after rescuing the woman who keeps appearing in his dreams."},
    {title: "Past Lives", caption: null, url: "./slidesImages/pastLivesX.jpg", desc: "Nora and Hao Sung have a complicated relationship. After falling in love as teenagers and separated by life's circumstances, they're affected as they try to reconnect in the future."},
]

export default slidesX;